HairMateApp/Controllers/SalonController.cs
using HairMateApp.Application.Interfaces;
using HairMateApp.Application.ViewModels.Salon;
using HairMateApp.Domain.Interface;
using HairMateApp.Domain.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using HairMateApp.Application.ViewModels.ReviewVm;
using Microsoft.AspNetCore.Authorization;

namespace HairMateApp.Controllers
{
    public class SalonController : Controller
    {
        private readonly ISalonService _salonService;
        private readonly UserManager<ApplicationUser> _userManager;

        public SalonController(ISalonService salonService, UserManager<ApplicationUser> userManager)
        {
            _salonService = salonService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int pageNo = 1, int pageSize = 10, string searchString = "", string salonGender = null)
        {
            List<Salon> salons;

            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);
                ViewBag.FullName = $"{user.FirstName} {user.LastName}";

                var userGender = user.Gender;
                var userRegion = user.Region;

                if (string.IsNullOrEmpty(salonGender))
                {
                    salonGender = userGender;
                }

                salons = await _salonService.GetSalonsByRegionAndGenderAsync(userRegion, salonGender);
            }
            else
            {
                salons = await _salonService.GetAllSalonsAsync();
            }

            var salonList = salons
                .Where(s => string.IsNullOrEmpty(searchString) || s.Name.Contains(searchString))
                .Skip(pageSize * (pageNo - 1))
                .Take(pageSize)
                .Select(s => new SalonForListVm
                {
                    SalonId = s.SalonId,
                    Name = s.Name,
                    LogoUrl = s.LogoUrl,
                    Description = s.Description,
                    Province = s.Province,
                    Type = s.Type,
                    City = s.City,
                    Street = s.Street
                }).ToList();

            var model = new ListSalonForListVm
            {
                PageSize = pageSize,
                CurrentPage = pageNo,
                SearchString = searchString,
                Salons = salonList,
                Count = salons.Count
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Redirect("https://localhost:7201/Identity/Account/AccessDenied");
            }
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var roles = await _userManager.GetRolesAsync(user);
                if (!roles.Contains("Admin") && !roles.Contains("Employee"))
                {
                    return Redirect("https://localhost:7201/Identity/Account/AccessDenied");
                }
                ViewBag.FullName = $"{user.FirstName} {user.LastName}";
            }
            else
            {
                return Redirect("https://localhost:7201/Identity/Account/Login");
            }
            return View(new NewSalonVm());
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.FullName = $"{user.FirstName} {user.LastName}";
            }

            var salon = await _salonService.GetSalonByIdAsync(id);
            if (salon == null)
            {
                return NotFound();
            }

            user = await _userManager.GetUserAsync(User);
            var canEdit = user != null && await _userManager.IsInRoleAsync(user, "Admin");
            var canManage = user != null && await _userManager.IsInRoleAsync(user, "Employee");

            var model = new SalonDetailsVm
            {
                SalonId = salon.SalonId,
                Name = salon.Name,
                LogoUrl = salon.LogoUrl,
                Description = salon.Description,
                Type = salon.Type,
                Province = salon.Province,
                City = salon.City,
                Street = salon.Street,
                PostalCode = salon.PostalCode,
                PaymentType = salon.PaymentType,
                Services = salon.Services ?? new List<Service>(),
                Reviews = salon.Reviews ?? new List<Review>(),
                Appointments = salon.Appointments ?? new List<Appointment>(),
                CanEdit = canEdit,
                CanManage = canManage,
                AverageRating = salon.Reviews.Any() ? Math.Round((decimal)salon.Reviews.Average(r => r.Rating), 1) : 0
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> BookAppointment(int salonId, DateTime date, TimeSpan time)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("https://localhost:7201/Identity/Account/Login");
            }

            var isAvailable = await _salonService.IsAppointmentAvailableAsync(salonId, date, time);
            if (!isAvailable)
            {
                return RedirectToAction("AppointmentUnavailable", new { salonId });

            }

            var appointment = new Appointment
            {
                SalonId = salonId,
                Date = date,
                Time = time,
                Status = "Booked",
                UserId = user.Id
            };

            var success = await _salonService.BookAppointmentAsync(appointment);
            if (!success)
            {
                TempData["Error"] = "An error occurred while booking the appointment.";
                return RedirectToAction("Details", new { id = salonId });
            }

            return RedirectToAction("BookedAppointments");
        }

        [HttpGet]
        public IActionResult AppointmentUnavailable(int salonId)
        {
            ViewBag.SalonId = salonId;
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> BookedAppointments()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                ViewBag.FullName = $"{user.FirstName} {user.LastName}";
            }
            else
            {
                return Redirect("https://localhost:7201/Identity/Account/Login");
            }
            var appointments = await _salonService.GetBookedAppointmentsAsync(user.Id);
            return View(appointments);
        }

        [HttpPost]
        public async Task<IActionResult> CancelAppointment(int appointmentId)
        {
            var success = await _salonService.CancelAppointmentAsync(appointmentId);
            if (!success)
            {
                // Handle error
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RescheduleAppointment(int appointmentId, DateTime newDate, TimeSpan newTime)
        {
            var success = await _salonService.RescheduleAppointmentAsync(appointmentId, newDate, newTime);
            if (!success)
            {
                // Handle error
            }

            return RedirectToAction("BookedAppointments");
        }

        [HttpPost]
        public async Task<IActionResult> CompleteAppointment(int appointmentId)
        {
            var success = await _salonService.CompleteAppointmentAsync(appointmentId);
            if (!success)
            {
                // Handle error
            }

            return RedirectToAction("BookedAppointments");
        }

        [HttpGet]
        public async Task<IActionResult> AddReview(int salonId)
        {
            var user = await _userManager.GetUserAsync(User);
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.FullName = $"{user.FirstName} {user.LastName}";
            }

            var model = new AddReviewVm
            {
                SalonId = salonId
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddReview(AddReviewVm model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("https://localhost:7201/Identity/Account/Login");
            }

            var review = new Review
            {
                SalonId = model.SalonId,
                Rating = model.Rating,
                Comment = model.Comment,
                UserId = user.Id,
                UserName = user.FirstName + " " + user.LastName,
            };

            var success = await _salonService.AddReviewAsync(review);
            if (!success)
            {
                TempData["Error"] = "An error occurred while adding the review.";
                return RedirectToAction("Details", new { id = model.SalonId });
            }

            return RedirectToAction("Details", new { id = model.SalonId });
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            ViewBag.FullName = $"{user.FirstName} {user.LastName}";
            var salon = await _salonService.GetSalonByIdAsync(id);
            if (salon == null)
            {

HairMateApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HairMateApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HairMateApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" />
    <style>
        body {
            font-family: 'Roboto', sans-serif;
        }

        header {
            background-color: #f8f9fa;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .navbar-brand {
            font-weight: 700;
        }

        .navbar-nav .nav-link {
            color: #007bff !important;
            transition: color 0.3s;
        }

            .navbar-nav .nav-link:hover {
                color: #0056b3 !important;
            }

        footer {
            background-color: #f8f9fa;
            box-shadow: 0 -4px 8px rgba(0, 0, 0, 0.1);
        }

        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            transition: background-color 0.3s, border-color 0.3s;
        }

            .btn-primary:hover {
                background-color: #0056b3;
                border-color: #004085;
            }
    </style>
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Salon" asp-action="Index">HairMateApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Salon" asp-action="BookedAppointments"><i class="fas fa-calendar-alt"></i> My visits</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Salon" asp-action="Create"><i class="fa fa-plus"></i> Add New Salon</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HairMateApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>